---
name: MojoX-Fixup-XHTML
version: 0.02
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: 'serves application/xhtml+xml content for L<Mojo>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  HTTP::Headers: 0
  HTTP::Negotiate: 0
  Mojo: 0.9
  Test::More: 0
provides:
  MojoX::Fixup::XHTML:
    file: lib/MojoX/Fixup/XHTML.pm
    version: 0.02
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
