---
name: Catalyst-Model-DBIC-Schema-QueryLog
version: 0.02
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: DBIx::Class::QueryLog Model Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Catalyst: 0
  Catalyst::Component::InstancePerContext: 0
  DBIx::Class::QueryLog: 0
  Moose: 0
  Sort::Key: 0
  Test::More: 0
provides:
  Catalyst::Model::DBIC::Schema::QueryLog:
    file: lib/Catalyst/Model/DBIC/Schema/QueryLog.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
