---
name: CatalystX-Foorum
version: 0.1.1
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Forum/BBS system based on Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  version: 0
provides:
  CatalystX::Foorum:
    file: lib/CatalystX/Foorum.pm
    version: 0.1.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
