---
name: TheSchwartz-Moosified
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: TheSchwartz based on Moose!
license: perl
resources:
  license: ~
build_requires:
  DBI: 0
  Moose: 0.57
  Scalar::Util: 0
  Test::More: 0
provides:
  TheSchwartz::Moosified:
    file: lib/TheSchwartz/Moosified.pm
    version: 0.03
  TheSchwartz::Moosified::Job:
    file: lib/TheSchwartz/Moosified/Job.pm
  TheSchwartz::Moosified::JobHandle:
    file: lib/TheSchwartz/Moosified/JobHandle.pm
  TheSchwartz::Moosified::Utils:
    file: lib/TheSchwartz/Moosified/Utils.pm
  TheSchwartz::Moosified::Worker:
    file: lib/TheSchwartz/Moosified/Worker.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
