---
name: Catalyst-Plugin-CHI
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: CHI wrap of Catalyst
license: perl
resources:
  license: ~
build_requires:
  CHI: 0
  Catalyst: 0
  Class::Data::Inheritable: 0
  MRO::Compat: 0
  Test::More: 0
provides:
  Catalyst::Plugin::CHI:
    file: lib/Catalyst/Plugin/CHI.pm
    version: 0.03
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
