---
name: Catalyst-Authentication-Store-FromSub-Hash
version: 0.02
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: A storage class for Catalyst Authentication using one Catalyst Model class (hash returned)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Catalyst: 0
  Catalyst::Plugin::Authentication: 0.10004
  Scalar::Util: 0
  Test::More: 0
provides:
  Catalyst::Authentication::Store::FromSub::Hash:
    file: lib/Catalyst/Authentication/Store/FromSub/Hash.pm
    version: 0.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
