---
name: Sphinx-Control
version: 0.02
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Simple class to manage a Sphinx searchd
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Moose: 0.32
  MooseX::Types::Path::Class: 0
  Test::More: 0
provides:
  Sphinx::Control:
    file: lib/Sphinx/Control.pm
    version: 0.02
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
