---
name: Lingua-Han-PinYin
version: 0.11
author:
  - 'Fayland, fayland@gmail.com'
abstract: Retrieve the Mandarin(PinYin) of Chinese character(HanZi).
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0
  Lingua::Han::Utils: 0.10
provides:
  Lingua::Han::PinYin:
    file: lib/Lingua/Han/PinYin.pm
    version: 0.11
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
