---
name: Pod-From-GoogleWiki
version: 0.06
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: convert from Google Code wiki markup to POD
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Text::SimpleTable: 0
provides:
  Pod::From::GoogleWiki:
    file: lib/Pod/From/GoogleWiki.pm
    version: 0.06
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
