---
name: Acme-PlayCode
version: 0.06
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Play code to win
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Moose: 0.57
  MooseX::Object::Pluggable: 0.0008
  PPI: 1.201
  Path::Class: 0.16
  Test::More: 0
provides:
  Acme::PlayCode:
    file: lib/Acme/PlayCode.pm
    version: 0.06
  Acme::PlayCode::Plugin::Averything:
    file: lib/Acme/PlayCode/Plugin/Averything.pm
    version: 0.05
  Acme::PlayCode::Plugin::DoubleToSingle:
    file: lib/Acme/PlayCode/Plugin/DoubleToSingle.pm
    version: 0.06
  Acme::PlayCode::Plugin::ExchangeCondition:
    file: lib/Acme/PlayCode/Plugin/ExchangeCondition.pm
    version: 0.04
  Acme::PlayCode::Plugin::PrintComma:
    file: lib/Acme/PlayCode/Plugin/PrintComma.pm
    version: 0.04
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
