---
name: Acme-CPANAuthors-Chinese
version: 0.01
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: CPAN 中国作者
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Acme::CPANAuthors: 0
  Test::More: 0
provides:
  Acme::CPANAuthors::Chinese:
    file: lib/Acme/CPANAuthors/Chinese.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
