# MySQL dump
# Generated by MySQLMan 1.09 (http://gossamer-threads.com/scripts/)
# Host: localhost    Database: foorum 
#--------------------------------------------------------

#
# Table structure for table 'board'
#
CREATE TABLE board (
  forum_id int(11)    ,
  page_id int(11)    ,
  order_no int(11)    ,
  category_id int(11)    ,
  UNIQUE forum_id (forum_id)
);

#
# Table structure for table 'category'
#
CREATE TABLE category (
  id int(11)    auto_increment,
  name varchar(255)    ,
  parent_id int(11)    ,
  level tinyint(4)    ,
  PRIMARY KEY (id)
);

#
# Table structure for table 'comment'
#
CREATE TABLE comment (
  comment_id int(11)    auto_increment,
  reply_to int(11)  DEFAULT ''  ,
  text text    ,
  post_on datetime    ,
  update_on datetime    ,
  post_ip varchar(32)    ,
  formatter varchar(16)  DEFAULT 'plain'  ,
  object_type varchar(30)  DEFAULT ''  ,
  object_id int(11)  DEFAULT ''  ,
  author_id int(11)    ,
  title varchar(255)  DEFAULT ''  ,
  forum_id int(11)    ,
  PRIMARY KEY (comment_id)
);

#
# Table structure for table 'email_setting'
#
CREATE TABLE email_setting (
  user_id int(11)  DEFAULT ''  ,
  object_type enum('comment','topic')  DEFAULT ''  ,
  frequence enum('daily','weekly','none')  DEFAULT ''  ,
  PRIMARY KEY (user_id,object_type)
);

#
# Table structure for table 'forum'
#
CREATE TABLE forum (
  forum_id int(11)    auto_increment,
  name varchar(100)    ,
  description varchar(100)    ,
  type varchar(16)    ,
  policy enum('public','private','protected')  DEFAULT 'public'  ,
  total_topics int(11)  DEFAULT '0'  ,
  total_replies int(11)  DEFAULT '0'  ,
  last_post_id int(11)    ,
  PRIMARY KEY (forum_id)
);

#
# Table structure for table 'message'
#
CREATE TABLE message (
  message_id int(11)    auto_increment,
  from_id int(11)    ,
  to_id int(11)    ,
  title varchar(255)  DEFAULT ''  ,
  text text  DEFAULT ''  ,
  post_on datetime  DEFAULT ''  ,
  post_ip varchar(32)  DEFAULT ''  ,
  PRIMARY KEY (message_id)
);

#
# Table structure for table 'message_unread'
#
CREATE TABLE message_unread (
  message_id int(11)    ,
  user_id int(11)  DEFAULT ''  
);

#
# Table structure for table 'page'
#
CREATE TABLE page (
  id int(11)    auto_increment,
  name varchar(255)    ,
  PRIMARY KEY (id)
);

#
# Table structure for table 'session'
#
CREATE TABLE session (
  id char(72)  DEFAULT ''  ,
  session_data text    ,
  expires int(11)  DEFAULT '0'  ,
  user_id int(11)    ,
  path varchar(255)    ,
  PRIMARY KEY (id)
);

#
# Table structure for table 'topic'
#
CREATE TABLE topic (
  topic_id int(11)    auto_increment,
  forum_id int(4)    ,
  title varchar(255)    ,
  closed enum('0','1')  DEFAULT '0'  ,
  sticky enum('0','1')  DEFAULT '0'  ,
  elite enum('0','1')  DEFAULT ''  ,
  hit int(11)  DEFAULT '0'  ,
  last_updator_id int(11)    ,
  last_update_date datetime  DEFAULT ''  ,
  author_id int(11)  DEFAULT ''  ,
  total_replies int(11)  DEFAULT '0'  ,
  PRIMARY KEY (topic_id)
);

#
# Table structure for table 'user'
#
CREATE TABLE user (
  user_id int(11)    auto_increment,
  username varchar(32)    ,
  password varchar(32)    ,
  nickname varchar(100)    ,
  gender enum('F','M','M')    ,
  birthday date    ,
  email varchar(255)    ,
  register_on datetime    ,
  register_ip varchar(32)    ,
  active_code char(10)    ,
  last_login_on datetime    ,
  last_login_ip varchar(32)    ,
  has_actived smallint(1)    ,
  login_times int(11)  DEFAULT '1'  ,
  homepage varchar(255)    ,
  status varchar(16)    ,
  threads int(11)  DEFAULT '0'  ,
  replies int(11)  DEFAULT '0'  ,
  last_post_id int(11)    ,
  PRIMARY KEY (user_id),
  UNIQUE username (username)
);

#
# Table structure for table 'user_role'
#
CREATE TABLE user_role (
  user_id int(11)    ,
  role enum('admin','moderator','user')  DEFAULT 'user'  ,
  field varchar(32)    
);

# ----------- Dump ends -----------