---
name: Pod-Simple-Wiki-Googlecode
version: 0.03
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: A class for creating Pod to Google Code Wiki filters.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Pod::Simple::Wiki: 0
  Test::More: 0
provides:
  Pod::Simple::Wiki::Googlecode:
    file: lib/Pod/Simple/Wiki/Googlecode.pm
    version: 0.03
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
