---
name: WWW-Zorpia-Journal
version: 0.01
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Post a journal to www.zorpia.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Spec: 0
  Test::More: 0
  WWW::Mechanize: 0
provides:
  WWW::Zorpia::Journal:
    file: lib/WWW/Zorpia/Journal.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
