---
name: Padre-Plugin-WordStats
version: 0.01
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: 'Word stats for L<Padre>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Padre: 0
  Test::More: 0
provides:
  Padre::Plugin::WordStats:
    file: lib/Padre/Plugin/WordStats.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
