---
name: WWW-Zorpia-Upload
version: 0.04
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: upload photos to www.zorpia.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  File::Spec: 0
  Test::More: 0
  WWW::Mechanize: 0
provides:
  WWW::Zorpia::Upload:
    file: lib/WWW/Zorpia/Upload.pm
    version: 0.04
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
